<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>*.interop</string>
	</array>
	<key>name</key>
	<string>interop</string>
	<key>patterns</key>
	<array>
		<dict>
            <key>include</key>
            <string>#comments</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#imports</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#app-name</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#package</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#keywords</string>
        </dict>
	</array>
    <key>repository</key>
    <dict>
      <!-- Comments -->  
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.interop</string>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.line.double-slash.interop</string>
            <key>begin</key>
            <string>//</string>
            <key>end</key>
            <string>$\n?</string>
          </dict>
        </array>
      </dict>
      <!-- Interop Keywords -->
      <key>keywords</key>
      <dict>
        <key>match</key>
        <string>\b(application|consumes|provides|from|to|option|as)\b</string>
        <key>name</key>
        <string>keyword.other.interop</string>
      </dict>
      <!-- Imports --> 
      <key>imports</key>
      <dict>
        <key>match</key>
        <string>\s*(import)\s+("[^"]+")\s*;</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.interop</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.unquoted.interop.package</string>
          </dict>
        </dict>
      </dict>
      <!-- App Name-->
      <key>app-name</key>
      <dict>
        <key>match</key>
        <string>\s*(application)\s+([\w]+)\s*{</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.interop</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.class.message.interop</string>
          </dict>
        </dict>                        
      </dict>
      <!-- Package -->
      <key>package</key>
      <dict>
        <key>match</key>
        <string>\s*(package)\s+([\w.]+)\s*;</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.interop</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.unquoted.interop.package</string>
          </dict>
        </dict>
      </dict>
    </dict>
	<key>scopeName</key>
	<string>text.interop</string>
</dict>
</plist>