<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>*.proto</string>
	</array>
	<key>name</key>
	<string>proto</string>
	<key>patterns</key>
	<array>
  	<dict>
        <key>include</key>
        <string>#syntax</string>
    </dict>
		<dict>
        <key>include</key>
        <string>#comments</string>
    </dict>
    <dict>
        <key>include</key>
        <string>#package</string>
    </dict>
    <dict>
        <key>include</key>
        <string>#imports</string>
    </dict>
    <dict>
        <key>include</key>
        <string>#message</string>
    </dict>
    <dict>
        <key>include</key>
        <string>#enum</string>
    </dict>
    <dict>
        <key>include</key>
        <string>#service</string>
    </dict>
	</array>
    <key>repository</key>
    <dict>
      <!-- Comments -->  
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.proto</string>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.line.double-slash.proto</string>
            <key>begin</key>
            <string>//</string>
            <key>end</key>
            <string>$\n?</string>
          </dict>
        </array>
      </dict>
      <!-- Method Keywords -->
      <key>methodKeywords</key>
      <dict>
        <key>match</key>
        <string>\s*(stream|returns)\s*</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.proto</string>
          </dict>
        </dict>
      </dict>
      <!-- Syntax -->
      <key>syntax</key>
      <dict>
        <key>match</key>
        <string>\s*(syntax)\s*=\s*("proto[23]")\s*;</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.proto</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.quoted.double.proto.syntax</string>
          </dict>
        </dict>
      </dict>
      <!-- Method -->
      <key>method</key>
      <dict>
        <key>begin</key>
        <string>(rpc)\s+([A-Za-z][A-Za-z0-9_]*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.proto</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}|;</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#methodKeywords</string>
          </dict>
        </array>
      </dict>
      <!-- Service -->
      <key>service</key>
      <dict>
        <key>begin</key>
        <string>(service)\s+([A-Za-z][A-Za-z0-9_.]*)\s*\{?</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.proto</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.class.message.proto</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#method</string>
          </dict>
        </array>
      </dict>
      <!-- Imports --> 
      <key>imports</key>
      <dict>
        <key>match</key>
        <string>\s*(import)\s+("[^"]+")\s*;</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.interop</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.unquoted.interop.package</string>
          </dict>
        </dict>
      </dict>
      <!-- Package -->
      <key>package</key>
      <dict>
        <key>match</key>
        <string>\s*(package)\s+([\w.]+)\s*;</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.proto</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.unquoted.proto.package</string>
          </dict>
        </dict>
      </dict>
      <!-- Map Field -->
      <key>mapfield</key>
      <dict>
        <key>begin</key>
        <string>\s*(map)\s*&lt;\s*([\w.]+)\s*,\s*([\w.]+)\s*&gt;\s+(\w+)\s*=\s*(\d+)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.proto</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.type.proto</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>storage.type.proto</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.other.proto</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.proto</string>
          </dict>
        </dict>
        <key>end</key>
        <string>;</string>
      </dict>
      <!-- Field -->
      <key>field</key>
      <dict>
        <key>begin</key>
        <string>\s*(optional|repeated|required)?\s*\b([\w.]+)\s+(\w+)\s*=\s*(\d+)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.proto</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.type.proto</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.other.proto</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.proto</string>
          </dict>
        </dict>
        <key>end</key>
        <string>;</string>
      </dict>
      <!-- Enum -->
      <key>enum</key>
      <dict>
        <key>begin</key>
        <string>(enum)(\s+)([A-Za-z][A-Za-z0-9_]*)(\s*)(\{)?</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.proto</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.class.proto</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
        </array>
      </dict>
      <!-- Message -->
      <key>message</key>
      <dict>
        <key>begin</key>
        <string>(message|extend)(\s+)([A-Za-z][A-Za-z0-9_.]*)(\s*)(\{)?</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.proto</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.class.message.proto</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#enum</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#mapfield</string>
          </dict>
        </array>
      </dict>
    </dict>
	<key>scopeName</key>
	<string>text.proto</string>
</dict>
</plist>