// <auto-generated>
// 	Generated by the Plexus Interop compiler.  DO NOT EDIT!
// 	source: interop\app_launcher_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code
namespace Plexus.Interop.Samples.GreetingClient.Generated {
	
	using System;
	using global::Plexus;
	using global::Plexus.Channels;
	using global::Plexus.Interop;
	using global::System.Threading.Tasks;
					
	internal static partial class AppLauncherService {
		
		public const string Id = "interop.AppLauncherService";			
		public const string LaunchMethodId = "Launch";
		
		public static readonly AppLauncherService.Descriptor DefaultDescriptor = CreateDescriptor();
		
		public static AppLauncherService.Descriptor CreateDescriptor() {
			return new AppLauncherService.Descriptor();
		} 
		
		public static AppLauncherService.Descriptor CreateDescriptor(string alias) {
			return new AppLauncherService.Descriptor(alias);
		}				
	
		public partial interface ILaunchProxy {
			IUnaryMethodCall<global::Plexus.Interop.Samples.GreetingClient.Generated.AppLaunchResponse> Launch(global::Plexus.Interop.Samples.GreetingClient.Generated.AppLaunchRequest request);
		}
		
		public partial interface ILaunchImpl {
			Task<global::Plexus.Interop.Samples.GreetingClient.Generated.AppLaunchResponse> Launch(global::Plexus.Interop.Samples.GreetingClient.Generated.AppLaunchRequest request, MethodCallContext context);
		}
		
		public sealed partial class Descriptor {
		
			public UnaryMethod<global::Plexus.Interop.Samples.GreetingClient.Generated.AppLaunchRequest, global::Plexus.Interop.Samples.GreetingClient.Generated.AppLaunchResponse> LaunchMethod {get; private set; }
			
			public Descriptor() {				
				LaunchMethod = Method.Unary<global::Plexus.Interop.Samples.GreetingClient.Generated.AppLaunchRequest, global::Plexus.Interop.Samples.GreetingClient.Generated.AppLaunchResponse>(Id, LaunchMethodId);
			}
		
			public Descriptor(string alias) {
				LaunchMethod = Method.Unary<global::Plexus.Interop.Samples.GreetingClient.Generated.AppLaunchRequest, global::Plexus.Interop.Samples.GreetingClient.Generated.AppLaunchResponse>(Id, alias, LaunchMethodId);
			}
		}
	}
					
}
#endregion Designer generated code
