=== Interop API call when service provider is not running

Let us see what happens when interop API is called, but target component (i.e. service provider) is not running:

[plantuml]
....
@startuml
skinparam monochrome true
autonumber
box "Browser tab A"
    participant "foo.com" as appA
    participant "Service API" as clientA
    participant "Interop Broker" as brokerA
    participant "App Launcher" as appLauncherA
    participant "Interop Transport" as transportA
end box
box "Browser tab A"
    participant "bar.com" as appB
    participant "Interop Broker" as brokerB
    participant "Interop Transport" as transportB
end box

appA -> clientA : invoke API method
clientA -> brokerA : send message as JSON
brokerA -> brokerA : check whether target \n component is alive
brokerA -> appLauncherA : request app launch
appLauncherA -> appB : open app URL in new tab
create brokerB
appB -> brokerB : create & init
create transportB
brokerB -> transportB : create & init
brokerB -> brokerB : generate component \n instance ID
brokerB -> transportB : handshake
transportB -> transportA : handshake
transportA -> brokerA : handshake
brokerA -> brokerA : register information about\nanother Broker instance
@enduml
....

TODO - detailed description