=== Initialization and simple point-to-point call

[plantuml]
....
@startuml
skinparam monochrome true
autonumber
box "Browser tab A"
    participant "foo.com" as appA
    participant "Plexus Core" as coreA
    participant "Interop Broker" as brokerA
    participant "Service API" as clientA
    participant "Interop Transport" as transportA
end box
participant "plexus.symphony.com" as backend
box "Browser tab B\n(simplified)"
    participant "Interop Transport" as transportB
    participant "Interop Broker" as brokerB
    participant "bar.com" as appB
end box

== Initialization ==
create coreA
appA -> coreA : load & init
create brokerA
coreA -> brokerA : create
brokerA -> backend : GET interop-registry.json
brokerA <-- backend: interop-registry.json
create clientA
brokerA -> clientA : dynamically generate
appA -> clientA : register API handlers
appA -> brokerA : connect()
create transportA
brokerA -> transportA : create & init
brokerA -> brokerA : generate unique\ncomponent instance ID
brokerB -> brokerB : generate unique\ncomponent instance ID
brokerB -> transportB : component\ninstance "alive"
transportB -> transportA : component\ninstance "alive"
transportA -> brokerA : component\ninstance "alive"

== Interop call ==
appA -> clientA : invoke API method
clientA -> brokerA : send message as JSON
brokerA -> brokerA : check that target\ncomponent is alive
brokerA -> transportA : send message
transportA ->  transportB : send message
transportB -> brokerB : send message

== App B shutdown ==
appB -> brokerB : disconnect
brokerB -> transportB : component\ninstance "dead"
transportB -> transportA : component\ninstance "dead"
transportA -> brokerA : component\ninstance "dead"
brokerA -> brokerA : remove component\ninstance from "alive" list

@enduml
....

TODO - details