ifdef::env-github,env-browser[:outFileSuffix: .adoc]

This introduction guide gets you started with Plexus Interop with a simple example of two apps which communicates with each other through Interop Broker:

- `vendorA.fx.CcyPairRateProvider` - app developed by Vendor A. The app provides FX pair exchange rates to other apps.
- `vendorB.fx.CcyPairRateViewer` - app developed by Vendor B in TypeScript. The app allows user to request FX pair exchange rate from other apps.

There is a quick start guide for all currently supported Plexus Interop Client's technologies:

- link:quick-start-web{outFileSuffix}[Quick Start - Web]
- link:quick-start-net{outFileSuffix}[Quick Start - .Net]

==== CCY Pair Rate Provider

First of all, both vendors need to agree and define common contract for FX rate providing service if it's not yet standardized and published.

Out of the box Plexus Interop uses https://developers.google.com/protocol-buffers/docs/reference/proto3-spec[Google Protocol Buffers Version 3] language to define messages and services.

Create folder "metadata" and put the following file with service and messages definitions into the folder:

[source, php]
./metadata/fx/CcyPairRateService.proto
----
syntax = "proto3";

package fx;

message CcyPair {
    string ccyPairName = 1;
}

message CcyPairRate {
    string ccyPairName = 1;
    double rate = 2;
}

service CcyPairRateService {
    rpc GetRate(CcyPair) returns (CcyPairRate);
}
----

==== Implement C# App

Each app integrated to Plexus Interop must define and publish interop manifest where it declares which services it consumes and which services it provides.
Published manifests then downloaded and used by Interop Brokers running on user machines.

Application can produce and consume many services simultaneously, but our example manifest is pretty straightforward as the app just implements one method.

Put the following interop manifest to "/metadata/vendorA/fx/CcyPairRateProvider.interop":

[source, php]
./metadata/vendorA/fx/CcyPairRateProvider.interop
----
package vendorA.fx;

import "fx/CcyPairRateService.proto";

application CcyPairRateProvider {
    provides fx.CcyPairRateService { GetRate; }
}
----

Let's create a simple app to demonstrate using of Plexus Interop API from C# app.
To do this, enter the following "dotnet" toolset command:

`dotnet new console -o VendorA.FX.CcyPairRateProvider`

The command will create folder "VendorA.FX.CcyPairRateProvider" with console C# application inside.
Navigate to the folder and invoke the following command to add Plexus.Interop.Client package:

`dotnet add VendorA.FX.CcyPairRateProvider\VendorA.FX.CcyPairRateProvider.csproj package Plexus.Interop.Client`

Ok, now we have application. Let's generate the code required for it according to interop manifest.
To do this we need java-based tool "plexusgen" and https://github.com/google/protobuf/releases[Protobuf compiler "protoc"]:

`java -jar plexusgen.jar --type=csharp --baseDir=metadata --input=metadata/vendorA/fx/CcyPairRateProvider.interop --namespace=VendorA.FX --output=VendorA.FX.CcyPairRateProvider --protoc=protoc.exe`

This command generates C# classes for all the messages referenced by the given interop manifest into the specified output folder, with the specified C# namespace.
In our case "VendorA.FX.CcyPair" and "VendorB.FX.CcyPairRate" classes are generated in file CcyPairRateService.cs. Note that you need to specify path to Protobuf compiler
using argument "--protoc" or place protoc compiler into the current folder.

Now we're ready to write the code. Add the following code to Program.cs:
[source, java]
./VendorA.FX.CcyPairRateProvider/Program.cs
----
using System;
using System.Threading.Tasks;
using Plexus.Interop;

namespace VendorA.FX.CcyPairRateProvider
{
    public sealed class Program
    {
        public static void Main(string[] args)
        {
            new Program().MainAsync(args).GetAwaiter().GetResult();
        }

        public async Task MainAsync(string[] args)
        {
            // Broker location to connect is specified
            // either in the first command line argument or in environment variable
            var brokerLocation = args.Length > 0
                ? args[0]
                : Environment.GetEnvironmentVariable("PLEXUS_BROKER_WORKING_DIR");

            // Defining client options
            var clientOptions = new ClientOptionsBuilder()
                .WithDefaultConfiguration(brokerLocation)
                .WithApplicationId("vendorA.fx.CcyPairRateProvider")
                .WithProvidedService("fx.CcyPairRateService", b =>
                    b.WithUnaryMethod<CcyPair, CcyPairRate>("GetRate", GetRateAsync))
                .Build();

            // Connecting
            var client = ClientFactory.Instance.Create(clientOptions);
            await client.ConnectAsync();
            Console.WriteLine("Connected. Waiting for requests. Press CTRL+C to disconnect.");
            Console.CancelKeyPress += (sender, eventArgs) => client.Dispose();

            // Awaiting completion
            await client.Completion;
            Console.WriteLine("Disconnected.");
        }

        private async Task<CcyPairRate> GetRateAsync(CcyPair request, MethodCallContext context)
        {
            Console.WriteLine("Received request: {0}", request);
            CcyPairRate response;
            switch (request.CcyPairName)
            {
                case "EURUSD":
                    response = new CcyPairRate
                    {
                        CcyPairName = "EURUSD",
                        Rate = 1.17
                    };
                    break;
                case "EURGBP":
                    response = new CcyPairRate
                    {
                        CcyPairName = "EURGBP",
                        Rate = 0.88
                    };
                    break;
                default:
                    response = new CcyPairRate
                    {
                        CcyPairName = "Unknown Pair"
                    };
                    break;
            }
            Console.WriteLine("Sending response: {0}", response);
            return response;
        }
    }
}
----

And finally, build the code:

`dotnet build -c release -r win-x86 -o ../CcyPairRateProvider VendorA.FX.CcyPairRateProvider`

This command will build our app to folder "CcyPairRateProvider".

==== Implement TypeScript App

Consumer manifest in our example is also very simple.

Put the following content to "metadata/vendorB/fx/CcyPairRateViewer.interop":

[source, php]
.metadata/vendorB/fx/CcyPairRateViewer.interop
----
package vendorB.fx;

import "fx/CcyPairRateService.proto";

application CcyPairRateViewer {
    consumes fx.CcyPairRateService { GetRate; }
}
----

Let's create Web App's folder and move to it
```
mkdir ccy-pair-rate-viewer
cd ccy-pair-rate-viewer
```
Now we can initialize our App's `npm` module running:
```
npm init
```
and passing default answers to all prompt questions. Then we need to install few compile:
```
npm i @plexus-interop/client @plexus-interop/websocket-transport --save
```
and dev dependencies:
```
npm i typescript browserify copyfiles electron trash-cli --save-dev
```
Let's also create basic tsconfig.json (Typescript Config) file and put it to the root:

[source, json]
./ccy-pair-rate-viewer/tsconfig.json
----
{
  "compilerOptions": {
    "target": "es6",
    "outDir": "dist/main",
    "rootDir": ".",
    "moduleResolution": "node",
    "module": "commonjs",
    "declaration": true,
    "pretty": true,
    "lib": ["es6", "dom"],
    "types": ["long"]
  },
  "include": [
    "src/**/*.ts",
    "tests/**/*.ts"
  ],
  "exclude": [
    "node_modules/**"
  ]
}
----

Then let's use code generation tool to generate Client's code for our application:
```
java -jar plexusgen.jar --type=ts --baseDir=../metadata --input=CcyPairRateViewer.interop --out=src/gen --protoc=./node_modules/.bin/pbts.cmd
```
Client's generated code will be saved to:
```
src/gen/CcyPairRateViewerGeneratedClient.ts
```
Let's create our main application's code, it will connect to broker, send request for Rate and print response:

[source, typescript]
./ccy-pair-rate-viewer/src/index.ts
----
import { CcyPairRateViewerClientBuilder, CcyPairRateViewerClient } from "./gen/CcyPairRateViewerGeneratedClient";
import { WebSocketConnectionFactory } from "@plexus-interop/websocket-transport";

// Read launch arguments, provided by Electron Launcher
declare var window: any;
const electron = window.require("electron")
const remote = electron.remote;
const webSocketUrl = remote.getCurrentWindow().plexusBrokerWsUrl;
const instanceId = remote.getCurrentWindow().plexusAppInstanceId;

new CcyPairRateViewerClientBuilder()
    // App's ID and Instance ID received from Launcher
    .withClientDetails({
        applicationId: "vendorB.fx.CcyPairRateViewer",
        applicationInstanceId: instanceId
    })
    // Pass Transport to be used for connecting to Broker
    .withTransportConnectionProvider(() => new WebSocketConnectionFactory(new WebSocket(webSocketUrl)).connect())
    .connect()
    .then((rateViewerClient: CcyPairRateViewerClient) => {
        // Client connected, we can use generated Proxy Service to perform invocation
        rateViewerClient.getCcyPairRateServiceProxy()
            .getRate({ccyPairName: "EURUSD"})
            .then(rateResponse => {
                document.body.innerText = `Received rate ${rateResponse.ccyPairName}-${rateResponse.rate}`;
            })
            .catch(e => console.log("Failed to receive rate", e))
    });
----

Let's also create simple HTML file to load result Javascript bundle from:
[source, html]
./ccy-pair-rate-viewer/index.html
----
<!DOCTYPE html>
<html>
<head>
    <title>CCY Rate Viewer</title>
    <script src="dist/rateViewer.bundle.js"></script>
</head>
<body>
</body>
</html>
----

Let's add simple build scripts to our `package.json` to compile the code and package everything to one bundle:
[source, json]
./ccy-pair-rate-viewer/package.json -> scripts
----
"scripts": {
    "prebuild": "trash dist",
    "compile": "tsc -p tsconfig.json", <1>
    "copy-gen-folders": "copyfiles src/gen/* dist/main", <2>
    "package": "browserify ./dist/main/src/index.js --outfile ./dist/rateViewer.bundle.js", <3>
    "build": "npm run compile && npm run copy-gen-folders && npm run package" <4>
  }
----
<1> Compile Typescript Code to JS
<2> Copy Generated messages to dist folder
<3> Package everything into one bundle
<4> Run all build steps together

Great! We are ready to build our application! Just call `build` command using `npm`:
```
npm run build
```

==== Register apps in App Registry

Dotnet app can be launched using built-in "interop.NativeAppLauncher". For web app we need to use ElectronAppLauncher.
Just copy folder "bin/win-x86/samples/apps/ElectronAppLauncher" into the current working folder.
Also we need Plexus Interop Broker. Copy folder "bin/win-x86/broker" into the current working folder.

Now we're ready to register both apps in app registry. To do this, create the app registry file "metadata/apps.json"
with the following content:

./metadata/apps.json
[source, js]
----
{
    "apps": [
        {
            "id": "interop.ElectronAppLauncher",
            "displayName": "Electron App Launcher",
            "launcherId": "interop.NativeAppLauncher",
            "launcherParams": {
                "cmd": "../ElectronAppLauncher/ElectronAppLauncher.exe",
                "args": ""
            }
        },
        {
            "id": "vendorA.fx.CcyPairRateProvider",
            "displayName": "Currency Pair Rate Provider",
            "launcherId": "interop.NativeAppLauncher",
            "launcherParams": {
                "cmd": "../CcyPairRateProvider/CcyPairRateProvider.exe",
                "args": ""
            }
        },
        {
            "id": "vendorB.fx.CcyPairRateViewer",
            "displayName": "Currency Pair Rate Viewer",
            "launcherId": "interop.ElectronAppLauncher",
            "launcherParams": {
                "path": "../ccy-pair-rate-viewer/dist/index.html"
            }
        }
    ]
}
----

==== Run the Example

Now we're ready to run the broker. The only required step is to generate interop.json file from our metadata.
This file is used by broker to verify interop invocations and perform service discovery.

To do this we need "plexusgen" tool again:

`java -jar plexusgen.jar --type=json_meta --baseDir=metadata --out=metadata`

Ok, now we're ready to launch our example. First start the broker and provide path to metadata folder:

`broker\plexus.exe broker .\metadata`

Then use electron launcher to start web app:

`ElectronAppLauncher\ElectronAppLauncher.exe -apps ../ccy-pair-rate-viewer/dist/index.html`

What should happen:
* CcyPairRateViewer invoke fx.CcyPairRateService.GetRate.
* Broker check that this service is implemented in CcyPairRateProvider and launch it.
* CcyPairRateProvider connect to broker and receive the invocation.
* CcyPairRateViewer receive the response.









