ifdef::env-github,env-browser[:outFileSuffix: .adoc]

In this section we will be going through the case of two simple business apps communicating with each other via Plexus Interop:

- `CcyPairRateProvider` - an app developed by Vendor A, which provides FX currency pair rates.
- `CcyPairRateViewer` - an app developed by Vendor B, which allows user to request FX currency pair rates from other apps and see them.

Two most popular cases for interoperability are web and .NET, so the guide is split into two independent sections:

- <<quick-start-web, Web (TypeScript)>>
- <<quick-start-dotnet, .NET (C#)>>.

Both guides describe the same flow/API, so if you want to experiment with interop between different technologies - just combine the samples, e.g. take web implementation of `CcyPairRateViewer` from the first guide and
.NET implementation of `CcyPairRateProvider` from the second guide and run them together.

===== Prerequisites

You will need the following software:

- Windows 7 or later
- http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[JDK 8+]
- https://nodejs.org/en/download/[Node.js 6+ with npm 3+] for web quick start
- https://www.microsoft.com/net/download/core[.NET Core 2.0 SDK x86] for .NET quick start

You also need to build Plexus Interop components if you have not done it yet. See <<how-to-build, How to build>> for details.

include::guides-quick-start-web.adoc[]

include::guides-quick-start-dotnet.adoc[]








