. Switch to the `bin\win-x86\quick-start` directory and start a new broker instance:
+
[source, bash]
----
cd bin\win-x86\samples\quick-start
start plexus broker
----
+
[NOTE]
====
Broker requires two types of metadata to run:

* *app registry* - declares all available apps and how to launch them. App Lifecycle Manager component uses this registry to launch apps when requested.
* *interop registry* - declares messages, services, and which of them are provided or consumed by each application. Broker uses this information to provide discovery capabilities and validate invocations between apps.

By default Interop Broker reads metadata from `apps.json` and `interop.json` files located in `metadata` sub-directory within broker's working directory. In real world scenarios, broker will load registries from remote server instead of local files, because remote server may provide many capabilities like (admin UI, central governance, audit trail, entitlements, etc.).
To load metadata from other data sources you need to implement your own *registry provider* (documentation on that is in progress).
====
+
[NOTE]
====
Each Interop Broker instance is identified by its working directory. It is possible to run many brokers in parallel,
but instance must run in a separate directory.
====