Like many other Remote Procedure Call (RPC) systems, Plexus is based around the idea of defining a service by specifying the methods that can be called remotely with their parameters and return types.

There are 4 possible types of RPC methods in Plexus mirroring types supported by http://www.grpc.io/docs/guides/concepts.html#rpc-life-cycle[gRPC]:

* Point-to-point call - consumer send a request, provider receives it, handles, and sends response back to the consumer.
* Provider streaming call - consumer sends one or many requests, provider sends only one response back.
* Consumer streaming call - consumer sends one request, provider sends many responses back.
* Bidirectional streaming call - consumer sends many requests, provider sends many responses.

However Plexus goes beyond what most RPC frameworks do:

* Plexus tracks the lifecycle of desktop apps, i.e. it knows if app is running or not and can launch app on demand.
* Plexus allows to define custom App Launchers, which allow fully custom installation, startup and shutdown flows
* Each app specified which interop services it provides and consumes. This way it is easy to track API usage and evolve APIs.
* Central Broker decouples apps from each other and allows dynamic discovery of service providers

==== Discovery flow

Step one: find API implementations:

[plantuml]
....
@startuml
skinparam monochrome true
[App A] -> [Interop Broker] : 1) discover API implementations
[Interop Broker] ..> [App A] : 2) apps B, C implement the API
[Interop Broker] .. [App B]
[Interop Broker] .. [App C]
[Interop Broker] .. [App D]
@enduml
....

Step two: select between API implementations

Step three: call specific API implementer:

[plantuml]
....
@startuml
skinparam monochrome true
[App A] -> [Interop Broker] : 1) call API provided by app B
[Interop Broker] --> [App B] : 2) launch app B
[Interop Broker] --> [App B] : 3) call API
[Interop Broker] .. [App C]
[Interop Broker] .. [App D]
@enduml
....

==== High-level architecture

[plantuml]
....
@startuml
skinparam monochrome true
node "User Machine" {
    component "App Instance" as appInstance {
        [App Functionality]
        [Interop Transport] as transportApp
        [Client Service API]
    }
    component "Plexus Host" {
        [Interop Broker]
        [Interop Transport]
        [App Launcher]
        [App Lifecycle Manager]
    }
}
cloud "Central Registries" {
    [App Registry]
    [Interop Registry]
}
[Interop API definitions] ..> [Client Service API] : generate
[Interop API definitions] ..> [Interop Registry] : publish
[App Registry] ..> [Interop Registry] : references
[Interop Registry] -> [Interop Broker] : load JSON
[App Registry] -> [App Lifecycle Manager] : load JSON
[Interop Broker] -> [App Lifecycle Manager] : request app launch
[Interop Broker] <-> [Interop Transport] : send/receive messages
[Interop Transport] <-> transportApp : send/receive messages
[Client Service API] <-> transportApp : send/receive  messages
[Client Service API] <-> [App Functionality] : send/receive messages
[App Lifecycle Manager] -> [App Launcher] : request app launch
[App Launcher] -> appInstance : start app
[App Launcher] -> [App Lifecycle Manager] : report app status

@enduml
....

==== Key elements

* *App Registry* - catalogue of apps, interop components within apps and _app launchers_
* *App Launcher* - component responsible for starting new app instances and tracking their lifecycle. Different app launchers should be used for different app technologies (e.g. .NET Launcher, Java Launcher, Python Launcher) or custom startup flows (e.g. launcher that knows how to download app from a special binary storage within organization).
* *App Lifecycle Manager* - central component that tracks all live app instances. All apps are started via App Lifecycle Managers, which selects an appropriate App Launcher and uses this Launcher to create a new instance of the app.
* *Interop API Definitions* - text files with formal definitions of interop APIs between apps, which define _messages_, _services_ and _applications_:
** *Message* - logical record of information, containing a series of name-value pairs (fields). Plexus uses Protobuf v3 protocol for defining and serializing messages.
** *Service* - set of related methods that can be provided by one or many applications. Plexus uses Protobuf v3 definition language syntax for defining services.
** *Application* - corresponds to a desktop application. Each application can provide services to other applications and consume services provided by other applications.
* *Interop Broker* - responsible for managing interop sessions, routing messages between apps and discovery mechanisms. If message was sent to component that is not running yet then Broker asks App Launcher to start the app using mapping between components and apps.
* *Interop Registry* - provides Interop Broker with all information about services, messages and connections between apps in run-time. Interop Registry is populated from *approved* Interop API Definitions.
* *App Registry* - provides App Lifecycle Manager with all information about how to launch apps: app launcher and launcher-specific parameters.
* *Interop Transport* - responsible for delivering serialized messages between Interop Broker and client interop APIs
* *Client Service API* - client library that app uses to provide some interop service or to consume interop service provided by another app. Service API is generated from interop API definitions. Depending on app technology API can be generated either in run-time (e.g. JavaScript) or in compile time (e.g. DLLs for .NET). Compile-time generation uses Plexus SDK tools.

==== Interop Broker

Interop broker is the central component working as a hub for all interop communications:

[plantuml]
....
@startuml
skinparam monochrome true
[Interop Broker] -up-> [App A] : send/receive\nmessages
[Interop Broker] -right-> [App B] : send/receive\nmessages
[Interop Broker] -down-> [App C] : send/receive\nmessages
[Interop Broker] -left-> [App D] : send/receive\nmessages
@enduml
....

Interop Broker has several responsibilities:

* It reads full information about all interoperability APIs from Interop Registry
* It routes interop API calls and replies between app instances
* It tracks which interop API implementations are alive. If some app calls a service which is not online yet then Broker launches service provider app via App Lifecycle Manager.

Note that Interop Broker is not talking with apps directly - it relies on Interop Transport, which can deliver serialized messages across app boundaries.