[[quick-start-net]]
==== Quick Start - .Net


Let's create a simple app to demonstrate using of Plexus Interop API from C# app.
To do this, enter the following "dotnet" toolset command:

`dotnet new console -o VendorA.FX.CcyPairRateProvider`

The command will create folder "VendorA.FX.CcyPairRateProvider" with console C# application inside.
Navigate to the folder and invoke the following command to add Plexus.Interop.Client package:

`dotnet add VendorA.FX.CcyPairRateProvider\VendorA.FX.CcyPairRateProvider.csproj package Plexus.Interop.Client`

Ok, now we have application. Let's generate the code required for it according to interop manifest.
To do this we need java-based tool "plexusgen" and https://github.com/google/protobuf/releases[Protobuf compiler "protoc"]:

`java -jar plexusgen.jar --type=csharp --baseDir=metadata --input=metadata/vendorA/fx/CcyPairRateProvider.interop --namespace=VendorA.FX --output=VendorA.FX.CcyPairRateProvider --protoc=protoc.exe`

This command generates C# classes for all the messages referenced by the given interop manifest into the specified output folder, with the specified C# namespace.
In our case "VendorA.FX.CcyPair" and "VendorB.FX.CcyPairRate" classes are generated in file CcyPairRateService.cs. Note that you need to specify path to Protobuf compiler
using argument "--protoc" or place protoc compiler into the current folder.

Now we're ready to write the code. Add the following code to Program.cs:
[source, java]
./VendorA.FX.CcyPairRateProvider/Program.cs
----
using System;
using System.Threading.Tasks;
using Plexus.Interop;

namespace VendorA.FX.CcyPairRateProvider
{
    public sealed class Program
    {
        public static void Main(string[] args)
        {
            new Program().MainAsync(args).GetAwaiter().GetResult();
        }

        public async Task MainAsync(string[] args)
        {
            // Broker location to connect is specified
            // either in the first command line argument or in environment variable
            var brokerLocation = args.Length > 0
                ? args[0]
                : Environment.GetEnvironmentVariable("PLEXUS_BROKER_WORKING_DIR");

            // Defining client options
            var clientOptions = new ClientOptionsBuilder()
                .WithDefaultConfiguration(brokerLocation)
                .WithApplicationId("vendorA.fx.CcyPairRateProvider")
                .WithProvidedService("fx.CcyPairRateService", b =>
                    b.WithUnaryMethod<CcyPair, CcyPairRate>("GetRate", GetRateAsync))
                .Build();

            // Connecting
            var client = ClientFactory.Instance.Create(clientOptions);
            await client.ConnectAsync();
            Console.WriteLine("Connected. Waiting for requests. Press CTRL+C to disconnect.");
            Console.CancelKeyPress += (sender, eventArgs) => client.Dispose();

            // Awaiting completion
            await client.Completion;
            Console.WriteLine("Disconnected.");
        }

        private async Task<CcyPairRate> GetRateAsync(CcyPair request, MethodCallContext context)
        {
            Console.WriteLine("Received request: {0}", request);
            CcyPairRate response;
            switch (request.CcyPairName)
            {
                case "EURUSD":
                    response = new CcyPairRate
                    {
                        CcyPairName = "EURUSD",
                        Rate = 1.17
                    };
                    break;
                case "EURGBP":
                    response = new CcyPairRate
                    {
                        CcyPairName = "EURGBP",
                        Rate = 0.88
                    };
                    break;
                default:
                    response = new CcyPairRate
                    {
                        CcyPairName = "Unknown Pair"
                    };
                    break;
            }
            Console.WriteLine("Sending response: {0}", response);
            return response;
        }
    }
}
----

And finally, build the code:

`dotnet build -c release -r win-x86 -o ../CcyPairRateProvider VendorA.FX.CcyPairRateProvider`

This command will build our app to folder "CcyPairRateProvider".
