:imagesdir: ./images

==== Send Unary Request

Executes Point-to-Point invocation, client receives response from server.

[source,javascript]
-------------------
sendUnaryRequest<Req, Res>(
    invocationInfo: InvocationDescriptor,
    requestMessage: Req,
    responseHandler: ValueHandler<Res>): Promise<InvocationClient>;
-------------------

*Parameters*

[horizontal]
invocationInfo:: details of remote action to execute
requestMessage:: simple object representing request details
responseHandler:: response/error handler

*Returns*

[horizontal]
invocationClient:: provides ability to cancel invocation, to notificate remote side that response no longer required

*Examples*

- Invoke remote action on any available provider:

[source,javascript]
-------------------
const invocationInfo: InvocationDescriptor = {
    serviceId: 'CcyRateService',
    methodId: 'GetRate'
};
const requestMessage = { ccyPairName: 'EURUSD' };
client.sendUnaryRequest<ICcyPair, ICcyPairRate>(invocationInfo, requestMessage, {
    value: pairRate => console.log(`Received rate ${pairRate.rate}`),
    error: e => console.error('Failed to get rate', e)
});
-------------------

- Invoke remote action on particular provider:

[source,javascript]
-------------------
const invocationInfo: InvocationDescriptor = {
    serviceId: 'CcyRateService',
    methodId: 'GetRate',
    // provider's app id, defined in metadata
    applicationId: 'RateProvider',
    // optional, if we want to pass invocation to particular running instance
    connectionId: remoteAppGuid
};
// same as in example above ...
-------------------

==== Register Unary Handler

Registers handler for provided unary method.

[source,javascript]
-------------------
onUnary<Req, Res>(
    serviceInfo: ServiceInfo,
    handler: UnaryInvocationHandler<Req, Res>): void;
-------------------

*Parameters*

[horizontal]
serviceInfo:: implemented service details
handler:: method details and provided implementation

*Examples*

- Register unary invocation handler
+
[source,javascript]
-------------------
const serviceInfo = { serviceId: 'CcyRateService' };
clientBuilder.onUnary<ICcyPair, ICcyPairRate>(serviceInfo, {
    methodId: 'GetRate',
    handle: async (invocationContext: MethodInvocationContext, request: ICcyPair) => {
        const rate: ICcyPairRate = await internalRateService.getRate(request.ccyPairName);
        return rate;
    }
};
-------------------

==== Discover Methods

Discovers available method invocation handlers.

[source,javascript]
-------------------
discoverMethod(discoveryRequest: MethodDiscoveryRequest): Promise<MethodDiscoveryResponse>;
-------------------

*Parameters*

[horizontal]
discoveryRequest:: discover criteria, defined in https://github.com/finos-plexus/plexus-interop/blob/master/protocol/plexus.interop.proto[client protocol]. All fields are optional, providing flexibility to search under different criteria.

*Returns*

[horizontal]
discoveryResponse:: discovered remote method implementations if any, containing extensive information on method provider. Discovered method instances can be passed to corresponding invocation methods.

*Examples*

- Discover by input message and invoke first available implementation:

[source,javascript]
-------------------
const discoveryResponse = await client.discoverMethod({
    inputMessageId: 'plexus.interop.CcyPair',
});
client.sendUnaryRequest<ICcyPair, ICcyPairRate>(
    discoveryResponse.methods[0],
    { ccyPairName: 'EURUSD' },
    {
        value: pairRate => console.log(`Received rate ${pairRate.rate}`),
        error: e => console.error('Failed to get rate', e)
    }
);
-------------------

NOTE: *Discovery Request* supports various of options, you can use any combinations of them.

- Discover by response type:

[source,javascript]
-------------------
const discoveryResponse = await client.discoverMethod({
    outputMessageId: 'plexus.interop.CcyPairRate'
});
-------------------

- Discover only online method handlers:

[source,javascript]
-------------------
const discoveryResponse = await client.discoverMethod({
    outputMessageId: 'plexus.interop.CcyPairRate',
    discoveryMode: DiscoveryMode.Online
});
-------------------

- Discover by method reference:

[source,javascript]
-------------------
const discoveryResponse = await client.discoverMethod({
    consumedMethod: {
        consumedService: {
            serviceId: 'CcyRateService'
        },
        methodId: 'GetRate'
    }
});
-------------------

- Implementing "broadcast" communication using discovery.

Using `discoveryMethod` as low level API we can easily implement sending of broadcast messages using following steps:

. Define method with `Empty` return type to be handled by listener components
+
[source,javascript]
-------------------
service CcyPairBroadcastService {
    rpc onCcyPairRate (CcyPairRate) returns (Empty);
}
-------------------

. Setup all listener apps as provider of this action. Also we can define specific Provider instances or even companies we would like to listen events from:
+
[source,javascript]
-------------------
application ListenerApp {
    // listen to message from any provider
    provides CcyPairBroadcastService {onCcyPairRate;}
    // or setup listener for providers from specific namespace
    // provides CcyPairBroadcastService to com.acme.* {onCcyPairRate;}
}
-------------------

. Setup broadcast publisher app to consume this action
+
[source,javascript]
-------------------
application RateProviderApp {
    consumes CcyPairBroadcastService {onCcyPairRate;}
}
-------------------

. Use online discovery to publish new rate to all connected consumers:
+
[source,javascript]
-------------------
async function broadcast(rate: CcyPairRate): Promise<void> {
    const discoveryResponse = await client.discoverMethod({
        consumedMethod: {
            consumedService: {
                serviceId: 'CcyPairBroadcastService'
            },
            methodId: 'onCcyPairRate'
        },
        discoveryMode: DiscoveryMode.Online
    });
    const responseHandler = {
        value: () => console.log('Delivered')
    };
    discoveryResponse.methods.forEach(method => {
        client.sendUnaryRequest<ICcyPairRate, Empty>(
            method,
            rate,
            responseHandler);
    });
}
-------------------

==== Discover Services

Discovers available service implementations. Provides ability to use few methods from particular provider together.

[source,javascript]
-------------------
discoverService(discoveryRequest: ServiceDiscoveryRequest): Promise<ServiceDiscoveryResponse>;
-------------------

*Parameters*

[horizontal]
discoveryRequest:: discover criteria, defined in https://github.com/finos-plexus/plexus-interop/blob/master/protocol/plexus.interop.proto[client protocol]. All fields are optional, providing flexibility to search under different criteria.

*Returns*

[horizontal]
discoveryResponse:: discovered remote service implementations if any, containing extensive information on method provider. Discovered method instances can be passed to corresponding invocation methods.

*Examples*

- Discover service, lookup for pair of methods to be used together:
+
[source,javascript]
-------------------
const discoveryResponse = client.discoverService({
    consumedService: {
        serviceId: 'CcyRateService'
    }
});
// choose service implementation, by provider id/service alias/other details
const service: DiscoveredService = serviceDiscoveryResponse
    .services
    .find(s => providedService.applicationId === 'RateProviderApp');
// choose required methods and invoke them as described above in 'Discover Methods' examples
const getRateMethod = service.methods.find(m => m.methodId === 'GetRate');
const getRateStreamMethod = service.methods.find(m => m.methodId === 'GetRateStream');
-------------------

- Discover only online service providers
+
[source,javascript]
-------------------
const discoveryResponse = client.discoverService({
    consumedService: {
        serviceId: 'CcyRateService'
    },
    discoveryMode: DiscoveryMode.Online
});
-------------------

==== Send Server Streaming Request

Executes Server Streaming invocation, client receives stream of messages from server.

[source,javascript]
------------------
sendServerStreamingRequest<Req, Res>(
    invocationInfo: InvocationDescriptor,
    requestMessage: Req,
    responseObserver: InvocationObserver<Res>): Promise<InvocationClient>;
------------------

*Parameters*

[horizontal]
invocationInfo:: details of remote action to execute
requestMessage:: simple object representing request details
responseObserver:: response stream observer

*Returns*

[horizontal]
invocationClient:: provides ability to cancel invocation, to notificate remote side that response no longer required

*Examples*

- Receive stream or rates from provider:
+
[source,javascript]
-------------------
const invocationInfo: InvocationDescriptor = {
    serviceId: 'CcyRateService',
    methodId: 'GetRateStream'
};
const requestMessage = { ccyPairName: 'EURUSD' };
client.sendServerStreamingRequest<ICcyPair, ICcyPairRate>(invocationInfo, requestMessage, {
    next: pairRate => console.log(`Received rate ${pairRate.rate}`),
    complete: () => console.log('Invocation completed'),
    error: e => console.error('Failed to get rate', e)
});
-------------------

==== Register Server Streaming Handler

Registers handler for provided server streaming method.

[source,javascript]
-------------------
onServerStreaming<Req, Res>(
    serviceInfo: ServiceInfo,
    handler: ServerStreamingInvocationHandler<Req, Res>): void;
-------------------

*Parameters*

[horizontal]
serviceInfo:: implemented service details
handler:: method details and provided implementation

*Examples*

- Register stream handler:
+
[source,javascript]
-------------------
const serviceInfo = { serviceId: 'CcyRateService' };
clientBuilder.onServerStreaming<ICcyPair, ICcyPairRate>(serviceInfo, {
    methodId: 'GetRateStream',
    handle: async (invocationContext: MethodInvocationContext,
            request: ICcyPair,
            hostClient: StreamingInvocationClient<ICcyPairRate>) => {
        const rate: ICcyPairRate = await internalRateService.getRate(request.ccyPairName);
        hostClient.next(rate);
        // send other rate
        const otherRate: ICcyPairRate = await internalRateService.getRate(request.ccyPairName);
        hostClient.next(otherRate);
        // complete streaming
        hostClient.complete();
    }
};
-------------------

==== Send Bidirectional Streaming Request

Executes Bidirectional Streaming invocation. Client and Server communicates using streams of messages.

[source,javascript]
-------------------
sendBidirectionalStreamingRequest<Req, Res>(
    invocationInfo: InvocationDescriptor,
    responseObserver: InvocationObserver<Res>): Promise<StreamingInvocationClient<Req>>;
-------------------

*Parameters*

[horizontal]
invocationInfo:: details of remote action to execute
responseObserver:: response stream observer

*Returns*

[horizontal]
streamingInvocationClient:: invocation client, provides ability to send stream of messages, complete or cancel invocation.

*Examples*

- Bidirectional communication, client updates server on requested ccy pairs and receives stream of rates from server:
+
[source,javascript]
-------------------
const invocationInfo: InvocationDescriptor = {
    serviceId: 'CcyRateService',
    methodId: 'GetRateBidiStream'
};
const invocation = await client.sendBidirectionalStreamingRequest<ICcyPair, ICcyPairRate>(
    invocationInfo,
    {
        next: pairRate => console.log(`Received rate ${pairRate.rate}`),
        streamCompleted: () => console.log('Remote stream completed'),
        complete: () => console.log('Invocation completed'),
        error: e => console.error('Failed to get rate', e)
    });
invocation.next({ ccyPairName: 'EURUSD' });
// ask for other ccy pair rates later
invocation.next({ ccyPairName: 'EURGBP' });
// notify server that no more pairs be requested
invocation.complete();
-------------------

==== Register Bidirectional Streaming Handler

Registers handler for provided bidirectional streaming method.

[source,javascript]
-------------------
onBidiStreaming<Req, Res>(
    serviceInfo: ServiceInfo,
    handler: BidiStreamingInvocationHandler<Req, Res>): void;
-------------------

*Parameters*

[horizontal]
serviceInfo:: implemented service details
handler:: method details and provided implementation

*Examples*

- Register bidirectional handler:
+
[source,javascript]
-------------------
const serviceInfo = { serviceId: 'CcyRateService' };
clientBuilder.onBidiStreaming<ICcyPair, ICcyPairRate>(serviceInfo, {
    methodId: 'GetRateStream',
    handle: (invocationContext: MethodInvocationContext,
            hostClient: StreamingInvocationClient<ICcyPairRate>) => {
        const ccyPairs = [];
        // send rate for each requested pair every second
        setInterval(() => {
            ccyPairs.forEach(pair => {
                hostClient.next(internalRateService.getRate(pair)
            });
        }, 1000);
        // client's stream observer
        return {
            next: ccyPair => ccyPairs.push(ccyPair)
        };
    }
};
-------------------

